# Generated by Django 4.0.5 on 2022-07-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TblCourse',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='TblCourseDetail',
            new_name='Detail',
        ),
    ]
