# Generated by Django 4.0.5 on 2022-07-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_tblcourse_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='is_finished',
        ),
    ]
